import { ErrorCode } from './constants';
import {
  NotAuthorized,
  NotFound,
  NotAuthenticated,
  ConflictError,
  PaymentError,
  ValidationError,
  UserInputError,
  ExternalApiError,
  SystemError,
  formatError,
  ActivityLogError,
  PermanentActivityLogError,
  APIFailureActivityLogError,
  MissingFieldActivityLogError,
  ExternalAPIAuthenticationFailActivityLogError,
  MissingExternalResourceActivityLogError,
  InternalAPIFailureActivityLogError,
  EmailActivityLogError,
  SMSActivityLogError,
  DBActivityLogError,
  RedisActivityLogError,
  InvestorOptOutActivityError,
} from './errors';
import { handleErrorSentryOptions, Sentry, withSentry } from './sentry';
import { convertErrorToCode, isSentryLevelError } from './utils';

export {
  Sentry,
  withSentry,
  NotAuthorized,
  NotFound,
  NotAuthenticated,
  ConflictError,
  PaymentError,
  ValidationError,
  UserInputError,
  ExternalApiError,
  SystemError,
  ActivityLogError,
  PermanentActivityLogError,
  APIFailureActivityLogError,
  MissingFieldActivityLogError,
  ExternalAPIAuthenticationFailActivityLogError,
  MissingExternalResourceActivityLogError,
  InternalAPIFailureActivityLogError,
  EmailActivityLogError,
  SMSActivityLogError,
  DBActivityLogError,
  RedisActivityLogError,
  InvestorOptOutActivityError,
  formatError,
  handleErrorSentryOptions,
  isSentryLevelError,
  ErrorCode,
  convertErrorToCode,
};
