storage: ./storage

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '@beforeyoubid/error-adapter':
    access: $all
    publish: $anonymous
  '**':
    access: $all
    proxy: npmjs
